### PR TITLE
chore: bump aws-sdk from v2 to v3

### PR DESCRIPTION
**Pull request by fedefrusc**
Fixes nearform/fastify-secrets-aws#367

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
The code changes LGTM although GitHub's security features are preventing tests from running, because variables used by the CI workflow are not being provided due to your changes living in a fork. I will approve and merge the PR, and we'll see if it works when merged in master. If it doesn't, we can do another iteration.

**Comment by simoneb** [comment]
@fedefrusc tests were mostly fine, but CI is failing due to missing coverage. You probably removed a test case where we were testing for a binary being returned by the API.

**Comment by fedefrusc** [comment]
@simoneb yes I had to change the test because of the new sdk version. I didn't notice the failed covarege. if you agree I'll do another PR, fixing the coverage.

**Comment by simoneb** [comment]
Yes please, go ahead.

**Pull request merged**
